= JavaWebMail

WTF? _Another_ web email client? Why?

This is meant to be the world's _most minimal mail messager_ for Java EE Web.
It only intends to:

. display a list of messages;
. view the text of a given message;
. reply to a message;
. compose a new message.

No attachments. No mailing lists or address book. Just the absolute bare bones.

Why? So it has few dependencies and is easy to install and maintain, that's why.
Well, that was the plan, initially. Dependency lists always seem to grow like Topsy.

Which leaves us with...

Because it's all I need - I mostly read email with IMAP, but sometimes have to
work behind crazy firewalls where only HTTP is permitted. So I need to be able
to peep at my messages, but that's all.

== Status

Connects, prints a few mail messages in the Inbox page, lets you view 
non-HTML messages in the Message page. Woohoo!

== How-To

. Pick a web app and context (subdirectory), and configure them:
.. For wildfly deployment, `cd src/main/webapp/WEB-INF; cp jb*sample jboss-web.xml; vi jb*.xml`
.. For other app servers, do what you do on them, or RTFM.
. mvn package
. Deploy. E.g, mvn wildfly:deploy
. Visit http://localhost:8080/yourMailContext

== TODO

. Worry, a lot, about formatting, and concomitant HTML security. Maybe show in raw, with a
button to view as HTML? Good security stance but may grow stale quickly.
. There must be a Delete button. Better: checklist, select multiple, then delete (or moveTo...).
. Maybe make messages (view and compose both) in a pop-up, so the list is always there?
. Cache the list so we don't re-fetch it on every Inbox view, as this seems to be very expensive.
. Performance: Handle more than 50 messages - it times out well before loading 1,000 messages, for example. May be a non-issue if we switch it to using mbox provider; use PrimeFaces datatable for sorting?.
. But with the mbox provider we have to handle authentication ourselves, with IMAP we use the IMAP account credentials.
. Handle non-default mboxes.
